Handle existing target directory

diff --git a/src/speck b/src/speck
--- a/src/speck
+++ b/src/speck
@@ -9,6 +9,18 @@ if [ $# -ne 2 ]; then
     exit 1
 fi
 
+# Remove the target directory if it exists, otherwise pandoc would fail.
+if [ -e "$2" ]; then
+    # Check that it was generated by us for safety.
+    if [ -e "$2/sitemap.json" ]; then
+        echo "Target directory exists, removing."
+        rm -rf "$2"
+    else
+        echo "Target directory exists and was not generated by SPECK."
+        exit 1
+    fi
+fi
+
 pandoc \
     --from markdown \
     --to chunkedhtml \
